### ISSUE TITLE
Truncating script names

### ISSUE THREAD

**Issue by gorjious** [ViktorRubenko/FastScripts#5]
Hello Viktor. I was running into an [issue](https://forum.glyphsapp.com/t/feature-request-narrower-sidebar/19723/5) with the sidebar being too wide and realized that is it has to do with the script names not truncating...would it be possible to add this feature? 

Seems like this is what should be happening based on the plugin images but it's not working on my version for some reason. I'm on 3.0.4 (3092)

<img width="285" alt="Screenshot 2021-07-24 at 14 45 00" src="https://user-images.githubusercontent.com/23149420/126866107-d8c36684-76e6-4eba-ab94-0eb0acb27ac5.png">

**Comment by ViktorRubenko** [comment]
https://forum.glyphsapp.com/t/feature-request-narrower-sidebar/19723/6
